source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AddressBookKit_Example' do
  pod 'AddressBookKit', :path => '../'
end

target 'AddressBookKit_Tests' do
  pod 'AddressBookKit', :path => '../'

  
end
