source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AddressBookKit_Example', :exclusive => true do
  pod 'AddressBookKit', :path => '../'
end

target 'AddressBookKit_Tests', :exclusive => true do
  pod 'AddressBookKit', :path => '../'

  
end
